### ISSUE TITLE
Need to install php5-curl in the docker container.

### ISSUE THREAD

**Issue by junguchina** [imtnd/testlink_dockerfile#1]
When you face the error after you add the issue tracker in the testlink,you need to install the php5-curl to fix the error.
The error msg:
```
[Thu Oct 26 05:29:47.127850 2017] [:error] [pid 10] [client 172.17.0.1:54540] PHP Fatal error:  Call to undefined function YouTrack\\curl_init() in /var/www/html/testlink/third_party/youtrackclient/src/connection.php on line 30, referer: http://localhost:80/testlink/lib/issuetrackers/issueTrackerView.php
```
Pls use below command：
```
apt-get install php5-curl
```
then restart the testlink docker container.
So suggest add the step in dockerfile php5-curl.
Thank you.

**Comment by imtnd** [comment]
Thank you for repoting the issue.

I added the command.
please verify the fix of this.
